# Variables
var_1: &docker_image circleci/node:10.4-browsers

anchor_1: &job_defaults
  working_directory: ~/personal-website
  docker:
    - image: *docker_image

version: 2
jobs:
  pre_build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install --no-progress
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: angular-lint
          command: npm run-script lint
      - store_artifacts:
          path: tslint.xml
          prefix: lint
      - run:
          name: angular-test
          command: npm run-script test-once
      - store_artifacts:
          path: test-results.xml
          prefix: tests

  build:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: angular-build --prod
          command: npm run-script build-prod

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: add-ssh-known-host
          command: ssh-keyscan $DROPLET_HOST >> ~/.ssh/known_hosts
      - run:
          name: deploy-over-ssh
          command: ssh $DROPLET_USER@$DROPLET_HOST "cd ~/personal_website; lib/deploy.sh"

workflows:
  version: 2
  default_workflow:
    jobs:
      - pre_build
      - build:
          requires:
            - pre_build
          filters:
            branches:
              only: master
      # - deploy:
      #     requires:
      #       - pre_build
      #       - build
      #     filters:
      #       branches:
      #         only: master
