version: 2.1

# Variables
job_defaults: &job_defaults
  working_directory: ~/personal-website
  docker:
    - image: circleci/node:12.3.1-browsers

commands:
  install_dependencies:
    description: "Install node modules (using cache)"
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
      #       - dependency-cache-{{ .Environment.CACHE_VERSION }}-
      - run:
          name: install-dependencies
          command: npm install --no-progress
      # - save_cache:
      #     key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules

jobs:
  lint:
    <<: *job_defaults
    steps:
      - install_dependencies
      - run:
          name: angular-lint
          command: npm run-script lint
      - store_artifacts:
          path: tslint.xml
          prefix: lint

  test:
    <<: *job_defaults
    steps:
      - install_dependencies
      - run:
          name: angular-test
          command: npm run-script test-once
      - store_artifacts:
          path: test-results.xml
          prefix: tests

  build:
    <<: *job_defaults
    steps:
      - install_dependencies
      - run:
          name: angular-build --prod
          command: npm run-script build-prod
      - save_cache:
          key: dist-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./dist

  deploy:
    working_directory: ~/personal-website
    machine: true
    steps:
      - restore_cache:
          keys:
            - dist-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: add-ssh-known-host
          command: ssh-keyscan $DROPLET_HOST >> ~/.ssh/known_hosts
      - run:
          name: remove-old-files
          command: ssh circleci@codyflatla.ca "rm -rf /var/www/codyflatla.ca/html/*"
      - run:
          name: deploy-using-scp
          command: |
            mv ~/personal-website/dist/assets/favicon ~/
            # -p preserves modification times, access times, and modes from the original file
            # -r recursively copy entire directories
            # -q quietly
            scp -prq ~/personal-website/dist/* circleci@codyflatla.ca:/var/www/codyflatla.ca/html/
            scp -prq ~/favicon/* circleci@codyflatla.ca:/var/www/codyflatla.ca/html/

workflows:
  version: 2
  default_workflow:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test
      - deploy:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only: master
