# Variables
var_1: &docker_image circleci/node:10.4-browsers

anchor_1: &job_defaults
  working_directory: ~/personal-website
  docker:
    - image: *docker_image

version: 2
jobs:
  lint:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install --non-interactive
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-lint
          command: yarn lint personal-website --tslint-config tslint.json
      - store_artifacts:
          path: tslint.xml
          prefix: lint

  test:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: angular-test
          command: yarn test personal-website --single-run --no-progress
      - store_artifacts:
          path: test-results.xml
          prefix: tests

  build:
    <<: *job_defaults
    steps:
      - checkout
      - run:
        name: angular-build --prod
        command: yarn build --prod --no-progress

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: add-ssh-known-host
          command: ssh-keyscan $DROPLET_HOST >> ~/.ssh/known_hosts
      - run:
          name: deploy-over-ssh
          command: ssh $DROPLET_USER@$DROPLET_HOST "cd ~/personal_website; lib/deploy.sh"

workflows:
  version: 2
  default_workflow:
    jobs:
      - lint
      - test
      - build:
        requires:
          - lint
          - test
        filters:
          branches:
            only: master
      # - deploy:
      #     requires:
      #       - lint
      #       - test
      #       - build
      #     filters:
      #       branches:
      #         only: master
